services:
  redis:
    image: redis:7-alpine
    container_name: redis1
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_USERNAME=mongoose1
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: